import * as React from "react";

export const genders = [
  { label: "Male", value: "male" },
  { label: "Female", value: "female" },
  { label: "Other", value: "other" },
];

export const states = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

// export const countries = [

//   "Albania",
//   "Andorra",
//   "Armenia",
//   "Austria",
//   "Azerbaijan",
//   "Belarus",
//   "Belgium",
//   "Bosnia & Herzegovina",
//   "Bulgaria",
//   "Croatia",
//   "Cyprus",
//   "Czech Republic",
//   "Denmark",
//   "Estonia",
//   "Finland",
//   "France",
//   "Georgia",
//   "Germany",
//   "Greece",
//   "Hungary",
//   "Iceland",
//   "Ireland",
//   "Italy",
//   "Kosovo",
//   "Latvia",
//   "Liechtenstein",
//   "Lithuania",
//   "Luxembourg",
//   "Macedonia",
//   "Malta",
//   "Moldova",
//   "Monaco",
//   "Montenegro",
//   "Netherlands",
//   "Norway",
//   "Poland",
//   "Portugal",
//   "Romania",
//   "Russia",
//   "San Marino",
//   "Serbia",
//   "Slovakia",
//   "Slovenia",
//   "Spain",
//   "Sweden",
//   "Switzerland",
//   "Turkey",
//   "Ukraine",
//   "United Kingdom",
//   "Vatican City",
// ];

export const sizes = [
  "X-Small",
  "Small",
  "Medium",
  "Large",
  "X-Large",
  "2X-Large",
];

export const sports = [
  "Baseball",
  "Basketball",
  "Cricket",
  "Field Hockey",
  "Football",
  "Table Tennis",
  "Tennis",
  "Volleyball",
];
